import http from 'node:http';
import { readFileSync,existsSync,mkdirSync,writeFileSync } from 'node:fs';
import { resolve,extname,join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { networkInterfaces } from 'node:os';
import { Engine,HttpError,validateEvent } from './src/engine.mjs';
import { EvidenceImages } from './src/evidence-images.mjs';
import { generateReport } from './src/reports.mjs';
import { Jev } from './src/jev.mjs';
import { RawTree } from './src/rawtree.mjs';
import { loadRules,refreshRules,fetchWeather,CACHED_WEATHER,WEATHER_URL } from './src/rules.mjs';
import { detect,liquidStatus,writeUpdate } from './src/vision.mjs';
const root=fileURLToPath(new URL('.',import.meta.url));process.chdir(root);
const session=existsSync('.runtime/active-session.json')?JSON.parse(readFileSync('.runtime/active-session.json','utf8')):{};if(!process.env.RAWTREE_TABLE&&session.table)process.env.RAWTREE_TABLE=session.table;
const rawtree=new RawTree();const jev=new Jev();let ruleData=await loadRules();const engine=new Engine(process.env.DATA_DIR||session.dataDir||join(root,'data/runtime'),ruleData.rules);
const images=new EvidenceImages({dir:engine.dir});
let flushing=false,initializing=false,initialized=false,refreshing=false,feedCache=null,feedPromise=null;
async function flush(){if(flushing||!process.env.RAWTREE_API_KEY)return;flushing=true;try{if(!initialized){await rawtree.init();initialized=true}while(engine.pending().length){const tx=engine.pending()[0];await rawtree.appendBatch(tx.records);engine.checkpoint()}feedCache=null}catch(error){console.error('RawTree sync deferred:',error.message)}finally{flushing=false}}
let decisionQueue=Promise.resolve();
function processEvent(input){const raw=validateEvent(input);const task=decisionQueue.then(async()=>{if(engine.events.has(raw.event_id))return engine.ingest(raw);let decision;try{decision=await jev.decide(raw,structuredClone(engine.state),engine.rules)}catch(error){console.error('Jev deterministic fallback:',error.message)}return engine.ingest(raw,decision)});decisionQueue=task.catch(()=>{});return task}
let writing=false;let pendingWriting=null;
async function scheduleWriter(id){pendingWriting=id;if(writing)return;writing=true;try{while(pendingWriting){const eventId=pendingWriting;pendingWriting=null;const revision=engine.state.revision;try{const update=await writeUpdate(engine.get(eventId),structuredClone(engine.state));if(engine.state.revision===revision){engine.enrich(eventId,update);void flush()}}catch(error){console.error('Liquid text fallback:',error.message)}}}finally{writing=false}}
async function getFeed(){if(!initialized||engine.pending().length)return {...engine.feed(),sync:{pending:engine.pending().length,detail:'Local durable outbox; RawTree sync pending'}};if(feedCache&&Date.now()-feedCache.at<1800)return feedCache.data;if(feedPromise)return feedPromise;feedPromise=(async()=>{try{const data={...await rawtree.feed(),source:'rawtree',sync:{pending:0}};feedCache={at:Date.now(),data};return data}catch{return {...engine.feed(),sync:{pending:engine.pending().length,detail:'RawTree query unavailable; local evidence shown'}}}finally{feedPromise=null}})();return feedPromise}
const send=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data))};
async function body(req){let total=0,chunks=[];for await(const chunk of req){total+=chunk.length;if(total>7_200_000)throw new HttpError(413,'Request too large');chunks.push(chunk)}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}')}catch{throw new HttpError(400,'Invalid JSON body')}}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.webm':'video/webm','.json':'application/json','.ico':'image/x-icon'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost'),path=url.pathname;res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');
 if(req.method==='POST'){if(req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host)throw new HttpError(403,'Cross-origin writes are not allowed');if(!req.headers['content-type']?.startsWith('application/json'))throw new HttpError(415,'Use application/json')}
 const imageMatch=path.match(/^\/api\/evidence-images\/([a-f0-9-]{36})$/);if(req.method==='GET'&&imageMatch){res.setHeader('Content-Type','image/jpeg');res.setHeader('Cache-Control','private, no-store');return res.end(await images.read(imageMatch[1]))}
 if(req.method==='GET'&&path==='/api/state')return send(res,200,engine.state);
 if(req.method==='GET'&&path==='/events')return send(res,200,await getFeed());
 if(req.method==='GET'&&path==='/api/rules')return send(res,200,ruleData);
 if(req.method==='GET'&&path==='/api/status'){const rs=rawtree.status;return send(res,200,{site_id:engine.state.site_id,integrations:{rawtree:{status:rs.connected?'live':rs.configured?'connecting':'offline',detail:rs.error||`${rs.database} · ${engine.pending().length} updates pending`},nimble:{status:ruleData.provenance?.provider==='nimble'?(ruleData.provenance.status==='verified'?'live':ruleData.provenance.status==='partial'?'partial':'error'):'fallback',detail:ruleData.provenance?.note||ruleData.provenance?.status||'Curated source rules; refresh to fetch Nimble evidence'},liquid:await liquidStatus(),jev:{...jev.status,status:jev.status.status==='connected'?'live':jev.status.status}},runtime:{uptime_seconds:Math.round(process.uptime()),outbox_pending:engine.pending().length,state_revision:engine.state.revision}})}
 if(req.method==='POST'&&path==='/events'){const event=await processEvent(await body(req));void flush();void scheduleWriter(event.event_id);return send(res,201,{...event,event,state_revision:engine.state.revision})}
 const verdictMatch=path.match(/^\/events\/([a-zA-Z0-9_.:-]+)\/(verdict|ack|correction|person)$/);if(req.method==='POST'&&verdictMatch){const data=await body(req);const event=verdictMatch[2]==='verdict'?engine.verdict(verdictMatch[1],data.verdict):verdictMatch[2]==='correction'?engine.correction(verdictMatch[1],data):verdictMatch[2]==='person'?engine.person(verdictMatch[1],data):engine.ack(verdictMatch[1]);void flush();void scheduleWriter(event.event_id);return send(res,200,{...event,event,state_revision:engine.state.revision})}
 if(req.method==='POST'&&['/api/detect','/detect/frame'].includes(path)){const input=await body(req);const detection=await detect(input.image);const raw=validateEvent({event_id:randomUUID(),ts:new Date().toISOString(),source:input.source||'browser-camera',type:'ppe_violation',zone:input.zone||'ZONE-A',person_label:input.person_label||'',detector_payload:detection});if(detection.workers_visible>0&&!detection.all_wearing_hardhats)raw.evidence_image=await images.save(raw.event_id,input.image);const e=await processEvent(raw);void flush();void scheduleWriter(e.event_id);return send(res,200,{detection,detector_payload:detection,event:e})}
 if(req.method==='POST'&&path==='/api/weather/refresh'){const input=await body(req);let raw=null,w;try{({raw,weather:w}=await fetchWeather())}catch(error){w={...CACHED_WEATHER,error:String(error.message).slice(0,200)}}if(input.test_wind_mph!==undefined)w={...w,wind_mph:Number(input.test_wind_mph),source:'test override'};const ts=new Date().toISOString();let raw_stored=false,raw_error=raw?null:'no live Nimble response';if(raw)await rawtree.appendBatch([{record_id:randomUUID(),kind:'world_weather',event_id:'world-weather',ts,provider:'nimble',url:WEATHER_URL,raw}]).then(()=>{raw_stored=true},error=>{raw_error=String(error.message).slice(0,200)});engine.setWeather({...w,updated_ts:ts});engine.persistState();return send(res,200,{weather:engine.state.weather,crane_zone:engine.state.zones.find(z=>z.zone_id==='ZONE-A'),raw_stored,raw_error})}
 if(req.method==='POST'&&path==='/api/rules/refresh'){if(refreshing)throw new HttpError(409,'Rules refresh is already running');refreshing=true;try{const before=JSON.stringify((ruleData.rules||[]).map(r=>r.evidence?.content_sha256||null));ruleData=await refreshRules();engine.rules=ruleData.rules;const changed=before!==JSON.stringify(ruleData.rules.map(r=>r.evidence?.content_sha256||null));engine.setRulesVersion({version:(engine.state.rules_version?.version||1)+(changed?1:0),changed,refreshed_at:new Date().toISOString(),label:changed?'Rules changed at live OSHA source; new version stored':'Rules refreshed from live source; content unchanged'});engine.persistState();return send(res,200,ruleData)}finally{refreshing=false}}
 if(req.method==='POST'&&path==='/api/report'){const input=await body(req);if(!['txt','docx'].includes(input.format))throw new HttpError(400,'Choose txt or docx');const report=await generateReport({events:[...engine.events.values()],state:engine.state,rules:ruleData,site:input.site,include_simulations:input.include_simulations===true,source:'Local durable journal'});res.writeHead(200,{'Content-Type':input.format==='txt'?'text/plain; charset=utf-8':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','Content-Disposition':`attachment; filename="sitelens-inspection-${new Date().toISOString().slice(0,10)}.${input.format}"`,'Cache-Control':'no-store'});return res.end(report[input.format])}
 if(req.method==='GET'&&path==='/api/evidence/export'){res.setHeader('Content-Disposition','attachment; filename="sitelens-evidence.json"');return send(res,200,{exported_at:new Date().toISOString(),...await getFeed(),state:engine.state,rules:ruleData})}
 if(req.method==='GET'&&path==='/health')return send(res,200,{ok:true,revision:engine.state.revision});
 if(req.method!=='GET'&&req.method!=='HEAD')throw new HttpError(404,'Endpoint not found');
 const filename=resolve(root,'public','.'+(path.endsWith('/')?path+'index.html':decodeURIComponent(path)));if(!filename.startsWith(join(root,'public')+'/')||!existsSync(filename))throw new HttpError(404,'Not found');const file=readFileSync(filename);res.writeHead(200,{'Content-Type':mime[extname(filename)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(req.method==='HEAD'?undefined:file);
 }catch(error){if(!res.headersSent)send(res,error.status||500,{error:error.status?error.message:'Unexpected server error'});else res.end();if(!error.status)console.error(error.message)}});
let port=Number(process.env.PORT||4317);let attempts=0;server.on('error',error=>{if(error.code==='EADDRINUSE'&&attempts++<20){port++;server.listen(port,'0.0.0.0')}else{console.error(error.message);process.exitCode=1}});server.on('listening',()=>{mkdirSync('.runtime',{recursive:true});writeFileSync('.runtime/server.json',JSON.stringify({port,url:`http://localhost:${port}`,pid:process.pid}));console.log(`SiteLens: http://localhost:${port}`);for(const entries of Object.values(networkInterfaces()))for(const i of entries||[])if(i.family==='IPv4'&&!i.internal)console.log(`Phone: http://${i.address}:${port}/phone.html`);void flush()});server.listen(port,'0.0.0.0');setInterval(()=>void flush(),10000).unref();
