import test from 'node:test';import assert from 'node:assert/strict';
import {buildReportModel,generateReport,renderTxt} from '../src/reports.mjs';
const event=(id,extra={})=>({event_id:id,ts:'2026-09-25T22:00:00Z',zone:'ZONE-A',source:'iphone-1',type:'ppe_violation',detector_payload:{violation:true,description:'Potential head protection concern'},decision:{violation:true,provider:'jev'},...extra});
test('report retains more than the dashboard 200 event limit',()=>{const model=buildReportModel({events:Array.from({length:237},(_,i)=>event(`event-${i}`))});assert.equal(model.records.length,237);assert.match(renderTxt(model),/event-236/);});
test('simulations explicit and scope counts recomputed',()=>{const input={events:[event('observed',{verdict:'confirmed'}),event('simulated',{source:'simulated-replay'})],metrics:{total_alerts:999,confirmed:999,source:'rawtree_sql'}};const all=buildReportModel(input);assert.match(renderTxt(all),/SIMULATED demonstration evidence/);const filtered=buildReportModel({...input,include_simulations:false});assert.equal(filtered.records.length,1);assert.equal(filtered.summary.find(f=>f.label==='Unsuppressed potential alerts included').value,'1');});
test('acknowledgement does not invent closure or missing inspection metadata',()=>{const txt=renderTxt(buildReportModel({events:[event('ack',{acknowledged:true})],site:{}}));assert.match(txt,/Inspector: Not recorded/);assert.match(txt,/Inspection date: Not recorded/);assert.match(txt,/Actual corrective action taken: Not recorded/);assert.match(txt,/Verified closure not established/);assert.match(txt,/Acknowledged receipt only/);});
test('corrective action and rule scope retained without inventing findings',()=>{const model=buildReportModel({events:[event('e',{enrichment:{rule_id:'r'},corrective_action:{action:'Barrier installed',owner:'Supplied supervisor',due_date:'2026-09-26',status:'completed',completed_at:'2026-09-25',verified_by:'Supplied reviewer'}})],rules:[{rule_id:'r',scope_note:'Only applicable where head injury exposure exists',plain_english_rule:'Protect against head injury',osha_citation:'1926.100(a)'}]});const txt=renderTxt(model);assert.match(txt,/Barrier installed/);assert.match(txt,/Only applicable/);assert.match(txt,/Correction and verifier recorded/);assert.match(txt,/not OSHA Form 300/);});
test('reports omit unknown properties and redact credentials in text',()=>{const txt=renderTxt(buildReportModel({site:{name:'rt_012345678901234567890123456789'},events:[event('safe',{api_key:'do-not-export'})]}));assert.ok(!txt.includes('do-not-export'));assert.ok(!txt.includes('rt_012345'));});
test('generates actual zipped DOCX and matching TXT',async()=>{const output=await generateReport({events:[],site:{name:'QA site'},generated_at:'2026-09-25T22:00:00Z'});assert.ok(Buffer.isBuffer(output.docx));assert.equal(output.docx.subarray(0,2).toString(),'PK');assert.match(output.txt,/QA site/);assert.match(output.txt,/No evidence records match/);});

test('report retains supplied preparer and inspection scope',()=>{const txt=renderTxt(buildReportModel({site:{prepared_by:'Supplied preparer',scope:'Zones A through E'}}));assert.match(txt,/Prepared by: Supplied preparer/);assert.match(txt,/Inspection scope: Zones A through E/);});
