import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
const base=process.env.SITELENS_URL||'https://sitelens-sim.vercel.app';
const checks=[];
async function api(path,body){const r=await fetch(base+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();assert.ok(r.ok,`${path}: ${JSON.stringify(data)}`);return data}
const id=`hosted-check-${randomUUID()}`;
const input={event_id:id,ts:new Date().toISOString(),source:'simulation',type:'focus4_scenario',zone:'ZONE-B',detector_payload:{violation:true,description:'SIMULATED acceptance check: backing vehicle enters an occupied zone.',rule_id:'VEHICLE-REVERSE',simulated:true,confidence:1}};
const e=await api('/events',input);assert.equal(e.event.enrichment.rule_id,'VEHICLE-REVERSE');assert.equal(e.event.decision.provider,'jev');checks.push('real Jev triage and correct OSHA mapping');
const before=await api('/api/state');await api('/events',input);const after=await api('/api/state');assert.equal(after.stats.events_today,before.stats.events_today);checks.push('idempotent submission');
await api(`/events/${id}/verdict`,{verdict:'confirmed'});await api(`/events/${id}/ack`,{});let state=await api('/api/state');assert.ok(state.zones[1].open_alert_count>0);checks.push('human verdict and receipt do not close hazard');
await api(`/events/${id}/correction`,{status:'completed',action:'SIMULATED: establish exclusion barrier and verify route before reversing',owner:'Acceptance-test role (simulated)',completed_at:new Date().toISOString(),verified_by:'Acceptance-test verifier (simulated)'});
const feed=await api('/events');const saved=feed.events.find(x=>x.event_id===id);assert.equal(saved.corrective_action.status,'completed');assert.equal(saved.closed,true);checks.push('verified closure survives evidence readback');
const site={name:'SiteLens demonstration',location:'Virtual training site',inspector:'Not a real inspection — automated acceptance check',prepared_by:'SiteLens acceptance test',inspection_date:new Date().toISOString().slice(0,10),scope:'Simulated construction hazards; not an actual workplace inspection'};
mkdirSync('artifacts/hosted',{recursive:true});
for(const format of ['txt','docx']){let r;for(let i=0;i<8;i++){r=await fetch(base+'/api/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({format,site,include_simulations:true})});if(r.ok)break;await new Promise(resolve=>setTimeout(resolve,1000))}assert.ok(r.ok,`Report ${r.status}`);const b=Buffer.from(await r.arrayBuffer());if(format==='docx')assert.equal(b.subarray(0,2).toString(),'PK');else{assert.ok(b.toString().includes(id));assert.match(b.toString(),/SIMULAT/i)}writeFileSync(`artifacts/hosted/site-inspection.${format}`,b)}checks.push('complete TXT and valid Word attachments');
const excluded=await fetch(base+'/api/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({format:'txt',site,include_simulations:false})});assert.ok(excluded.ok);assert.ok(!(await excluded.text()).includes(id));checks.push('simulations excluded by default report scope');
if(process.env.TEST_CAMERA==='1'){const detection=await api('/api/detect',{image:'data:image/png;base64,'+readFileSync('tests/fixtures/blank.png').toString('base64'),zone:'ZONE-A'});assert.equal(detection.detection.violation,false);assert.equal(detection.detection.runtime,'local-edge-worker');assert.equal(detection.event.decision.provider,'jev');checks.push('hosted photo → private queue → actual local Liquid → Jev → durable evidence')}
for(const path of ['/.env','/server.mjs','/src/engine.mjs']){const r=await fetch(base+path);assert.equal(r.status,404)}checks.push('private files unavailable through deployment');
const health=await api('/health');assert.equal(health.persistence,'private-vercel-blob');const result={passed:true,url:base,checked_at:new Date().toISOString(),event_id:id,checks};writeFileSync('artifacts/hosted/smoke.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
