import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const base=process.env.SITELENS_URL||'http://localhost:4317';
async function api(path,body){const r=await fetch(base+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();assert.ok(r.ok,`${path}: ${JSON.stringify(data)}`);return data}
const payload=(id,confidence,pattern)=>({event_id:id,ts:new Date().toISOString(),source:'smoke-simulated',type:'ppe_violation',zone:'ZONE-A',detector_payload:{workers_visible:1,all_wearing_hardhats:false,all_wearing_hiviz:true,violation:true,description:'A visible worker without a hardhat in the configured construction hazard zone.',confidence,pattern}});
const id=randomUUID(),pattern='smoke-glare-'+id.slice(0,8);const a=await api('/events',payload('smoke-'+id,.98,'missing_hardhat'));assert.equal(a.decision.provider,'jev');assert.equal(a.decision.violation,true);assert.equal(a.suppressed,false);await api(`/events/${a.event_id}/verdict`,{verdict:'confirmed'});await api(`/events/${a.event_id}/ack`,{});
const b=await api('/events',payload('smoke-glare-'+id,.5,pattern));assert.equal(b.suppressed,false);await api(`/events/${b.event_id}/verdict`,{verdict:'false_alarm'});const c=await api('/events',payload('smoke-repeat-'+id,.5,pattern));assert.equal(c.suppressed,true);
const image='data:image/png;base64,'+readFileSync('tests/fixtures/blank.png').toString('base64');const camera=await api('/api/detect',{image,source:'smoke-blank-frame',zone:'ZONE-A'});assert.equal(camera.detection.violation,false);assert.equal(camera.event.decision.provider,'jev');
let feed;for(let i=0;i<40;i++){feed=await api('/events');if(feed.source==='rawtree'&&feed.events.some(e=>e.event_id===c.event_id&&e.suppressed)&&feed.events.some(e=>e.event_id===a.event_id&&e.verdict==='confirmed'&&e.acknowledged))break;await new Promise(r=>setTimeout(r,1000))}
assert.equal(feed.source,'rawtree');assert.ok(feed.events.some(e=>e.event_id===a.event_id&&e.verdict==='confirmed'));assert.ok(feed.events.some(e=>e.event_id===c.event_id&&e.suppressed));const state=await api('/api/state');assert.ok(state.zones[0].suppression_rules.some(r=>r.pattern===pattern));assert.ok(feed.metrics.total_alerts>0);
const status=await api('/api/status');assert.ok(['rawtree','nimble','liquid','jev'].every(k=>status.integrations[k].status==='live'));const exportData=await api('/api/evidence/export');assert.ok(exportData.events.length);const report={pass:true,checked_at:new Date().toISOString(),checks:['live Jev typed decisions','confirm and acknowledge','human-gated suppression','real Liquid image inference','RawTree SQL read-back and metrics','all four integrations live','evidence export'],event_ids:[a.event_id,b.event_id,c.event_id,camera.event.event_id],jev_latency_ms:a.decision.latency_ms,liquid_inference_ms:camera.detection.inference_ms,metrics:feed.metrics,state_bytes:state.context_metrics.state_bytes,status};mkdirSync('artifacts',{recursive:true});writeFileSync('artifacts/smoke.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
