import {Engine,HttpError,validateEvent} from './engine.mjs';
import {CloudStore} from './cloud-store.mjs';
import {RawTree} from './rawtree.mjs';
import {Jev} from './jev.mjs';
import {loadRules,fetchWeather,CACHED_WEATHER,WEATHER_URL} from './rules.mjs';
import {randomUUID,createHash} from 'node:crypto';

/** Blob owns operational state/outbox; RawTree owns the complete evidence history. */
export class CloudService {
 constructor({store,rawtree=new RawTree(),jev=new Jev(),rules}={}){this.store=store||new CloudStore({path:process.env.STATE_BLOB_PATH||'sitelens/production-state-v1.json'});this.rawtree=rawtree;this.jev=jev;this.rules=rules;this.ready=null}
 async initialize(){this.rules ||= await loadRules();if(!this.ready)this.ready=this.rawtree.init().catch(error=>{this.ready=null;throw error});await this.ready}
 async read(){this.rules ||= await loadRules();const {value}=await this.store.read();return {snapshot:value||{},engine:Engine.fromSnapshot(value,value?.rules?.rules||this.rules.rules)}}
 async mutate(fn){await this.initialize();let result;const snapshot=await this.store.update(async previous=>{const engine=Engine.fromSnapshot(previous,previous?.rules?.rules||this.rules.rules);result=await fn(engine);return {...previous,...engine.snapshot()}});await this.flush().catch(()=>{});return {event:result,state:snapshot.state}}
 async hydrate(engine,id){if(engine.events.has(id))return;const event=await this.rawtree.getEvent(id);if(event)engine.events.set(id,event)}
 async ingest(input){const raw=validateEvent(input);return this.mutate(async engine=>{await this.hydrate(engine,raw.event_id);if(engine.events.has(raw.event_id))return engine.ingest(raw);let decision;try{decision=await this.jev.decide(raw,engine.state,engine.rules)}catch{}return engine.ingest(raw,decision)})}
 async action(id,action,input){return this.mutate(async engine=>{await this.hydrate(engine,id);return action==='verdict'?engine.verdict(id,input.verdict):action==='ack'?engine.ack(id):action==='person'?engine.person(id,input):engine.correction(id,input)})}
 async flush(){await this.initialize();const {value}=await this.store.read();const records=value?.outbox||[];if(!records.length)return;for(let i=0;i<records.length;i+=100)await this.rawtree.appendBatch(records.slice(i,i+100));const sent=new Set(records.map(r=>r.record_id));if(await this.rawtree.visibleRecordCount(records)!==sent.size)throw new HttpError(503,'Evidence indexing; retry shortly');await this.store.update(value=>({...value,outbox:(value?.outbox||[]).filter(r=>!sent.has(r.record_id))}))}
 async feed(){await this.initialize();await this.flush().catch(()=>{});const {snapshot,engine}=await this.read();try{const data=engine.state.revision?await this.rawtree.feed():{events:[],metrics:{total_alerts:0,confirmed:0,precision:null}};const merged=new Map(data.events.map(e=>[e.event_id,e]));for(const e of engine.events.values())merged.set(e.event_id,e);return {...data,events:[...merged.values()].sort((a,b)=>b.ts.localeCompare(a.ts)).slice(0,200),source:'rawtree',sync:{pending:snapshot.outbox?.length||0}}}catch(error){return {...engine.feed(),source:'durable-cache',sync:{pending:snapshot.outbox?.length||0,detail:'RawTree unavailable; latest 200 persisted events shown'}}}}
 async reportInput(){await this.initialize();await this.flush();const {snapshot,engine}=await this.read();if(snapshot.outbox?.length)throw new HttpError(503,'Evidence indexing; retry shortly');const events=engine.state.revision?await this.rawtree.allEvents():[];const merged=new Map(events.map(e=>[e.event_id,e]));for(const e of engine.events.values())merged.set(e.event_id,e);if(merged.size<(engine.state.evidence_count||0))throw new HttpError(503,'Evidence history is still indexing; retry shortly');return {events:[...merged.values()],state:engine.state,rules:snapshot.rules||this.rules,source:'RawTree complete evidence history with durable pending updates'}}
 async saveRules(rules){const hash=r=>createHash('sha256').update(JSON.stringify((r?.rules||[]).map(x=>[x.rule_id,x.evidence?.content_sha256||null]))).digest('hex').slice(0,12);const {snapshot,engine}=await this.read();const previous=hash(snapshot.rules||this.rules),current=hash(rules),changed=previous!==current,ts=new Date().toISOString();await this.rawtree.appendBatch([{record_id:randomUUID(),kind:'world_rules',event_id:'world-rules',ts,provider:'nimble',content_hash:current,provenance:rules.provenance,rules:rules.rules}]).catch(()=>{});await this.store.update(value=>({...value,rules}));this.rules=rules;await this.mutate(e=>e.setRulesVersion({version:(engine.state.rules_version?.version||1)+(changed?1:0),content_hash:current,changed,refreshed_at:ts,label:changed?'Rules changed at live OSHA source; new version stored':'Rules refreshed from live source; content unchanged'}));return rules}
 async weather(testWind){let raw=null,w;try{({raw,weather:w}=await fetchWeather())}catch(error){w={...CACHED_WEATHER,error:String(error.message).slice(0,200)}}if(Number.isFinite(testWind))w={...w,wind_mph:testWind,source:'test override'};const ts=new Date().toISOString();await this.initialize().catch(()=>{});let raw_stored=false,raw_error=raw?null:'no live Nimble response';if(raw)await this.rawtree.appendBatch([{record_id:randomUUID(),kind:'world_weather',event_id:'world-weather',ts,provider:'nimble',url:WEATHER_URL,raw}]).then(()=>{raw_stored=true},error=>{raw_error=String(error.message).slice(0,200)});const {state}=await this.mutate(e=>e.setWeather({...w,updated_ts:ts}));return {weather:state.weather,crane_zone:state.zones.find(z=>z.zone_id==='ZONE-A'),raw_stored,raw_error}}
}
