import { isDeepStrictEqual } from 'node:util';
import { mkdirSync, existsSync, readFileSync, appendFileSync, writeFileSync, renameSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
const now=()=>new Date().toISOString();
const copy=x=>structuredClone(x);
export class HttpError extends Error { constructor(status,message){super(message);this.status=status;} }
const invalid=message=>{throw new HttpError(400,message)};
export function validateEvent(input){
 if(!input||typeof input!=='object'||Array.isArray(input))invalid('Expected an event object');
 if('kind' in input||'record_id' in input)invalid('kind and record_id are reserved storage fields');
 const e=copy(input); if(e.person_label!==undefined&&(typeof e.person_label!=='string'||e.person_label.length>120))invalid('Person label must be at most 120 characters');if(e.evidence_image!==undefined&&(!e.evidence_image||typeof e.evidence_image.url!=='string'||!/^\/api\/evidence-images\/[a-f0-9-]{36}$/.test(e.evidence_image.url)))invalid('Invalid evidence image reference'); for(const field of ['event_id','source'])if(typeof e[field]!=='string'||! /^[a-zA-Z0-9_.:-]{1,100}$/.test(e[field]))invalid(`Invalid ${field}`);
 if(!/^ZONE-[A-E]$/.test(e.zone))invalid('Only ZONE-A through ZONE-E are configured');
 if(!['ppe_violation','focus4_scenario'].includes(e.type))invalid('Invalid event type');
 if(typeof e.ts!=='string'||!Number.isFinite(Date.parse(e.ts)))invalid('Invalid timestamp');
 e.ts=new Date(e.ts).toISOString();
 const p=e.detector_payload;if(!p||typeof p!=='object'||Array.isArray(p))invalid('detector_payload required');
 if(typeof p.violation!=='boolean')invalid('violation must be boolean');
 if(typeof p.description!=='string'||p.description.length>1000)invalid('description must be a string of at most 1000 characters');
 if(p.confidence!==undefined && (typeof p.confidence!=='number'||!Number.isFinite(p.confidence)||p.confidence<0||p.confidence>1))invalid('confidence must be between 0 and 1');
 if(p.workers_visible!==undefined&&(!Number.isInteger(p.workers_visible)||p.workers_visible<0||p.workers_visible>10000))invalid('Invalid workers_visible');
 for(const key of ['all_wearing_hardhats','all_wearing_hiviz'])if(p[key]!==undefined&&typeof p[key]!=='boolean')invalid(`${key} must be boolean`);
 if(p.pattern!==undefined&&(typeof p.pattern!=='string'||p.pattern.length>80))invalid('pattern must be a string of at most 80 characters');
 if(JSON.stringify(e).length>16000)invalid('Event too large');
 return e;
}
export function initialState(){return {site_id:'SITELENS-DEMO',revision:0,evidence_count:0,shift_date:now().slice(0,10),zones:['A','B','C','D','E'].map(id=>({zone_id:'ZONE-'+id,status:'clear',active_hazards:[],last_change_ts:now(),confidence_threshold:.65,severity_weight:1,suppression_rules:[],open_alert_count:0,unacknowledged_count:0})),open_alerts:[],open_alert_count:0,omitted_open_alerts:0,shift_summary:'Monitoring five zones. No detections have been received. Human verdicts will guide future triage.',stats:{events_today:0,acks:0,false_alarms:0,confirmed:0,suppressed:0,total_alerts:0},context_metrics:{state_bytes:0,estimated_state_tokens:0,naive_bytes:0,estimated_naive_tokens:0}};}
export class Engine{
 constructor(dir,rules){this.dir=dir;this.rules=rules;this.events=new Map();this.state=initialState();this.transactions=[];this.synced=0;if(!dir){this.journal=null;return}mkdirSync(dir,{recursive:true});this.journal=join(dir,'journal.jsonl');
  if(existsSync(this.journal)){const lines=readFileSync(this.journal,'utf8').split('\n');for(let i=0;i<lines.length;i++){if(!lines[i])continue;let tx;try{tx=JSON.parse(lines[i])}catch(err){if(i===lines.length-1){writeFileSync(this.journal,lines.slice(0,i).join('\n')+'\n');break}throw new Error(`Corrupt journal at line ${i+1}`)}this.transactions.push(tx);this.state=tx.state;if(tx.event)this.events.set(tx.event.event_id,tx.event);}}
  const checkpoint=join(dir,'outbox-checkpoint.json');if(existsSync(checkpoint))this.synced=Math.min(JSON.parse(readFileSync(checkpoint,'utf8')).synced,this.transactions.length);
 }
 commit(event,records,summary){this.state.revision++;this.rewrite();if(summary){this.state.shift_summary=summary;this.state.summary_writer='Liquid LFM2.5-VL-450M'}for(let i=0;i<2;i++){this.state.context_metrics.state_bytes=Buffer.byteLength(JSON.stringify(this.state));this.state.context_metrics.estimated_state_tokens=Math.ceil(this.state.context_metrics.state_bytes/4)}const tx={event:copy(event),records:records.map(r=>({...r,record_id:r.record_id||randomUUID()})),state:copy(this.state)};tx.records.push({record_id:randomUUID(),kind:'state',event_id:event.event_id,ts:now(),state:copy(this.state)});if(this.journal)appendFileSync(this.journal,JSON.stringify(tx)+'\n',{flush:true});this.transactions.push(tx);this.events.delete(event.event_id);this.events.set(event.event_id,event);this.persistState();return copy(event)}
 persistState(){if(!this.dir)return;writeFileSync(join(this.dir,'state.tmp'),JSON.stringify(this.state,null,2));renameSync(join(this.dir,'state.tmp'),join(this.dir,'state.json'))}
 rewrite(){const s=this.state,learnedCount=s.zones.reduce((n,z)=>n+z.suppression_rules.length,0);s.summary_writer='template';s.omitted_open_alerts=Math.max(0,s.open_alert_count-s.open_alerts.length);s.shift_summary=`The site has processed ${s.stats.events_today} detections this shift, with ${s.open_alert_count} alerts awaiting corrective closure. Reviewers confirmed ${s.stats.confirmed} and rejected ${s.stats.false_alarms} alerts; ${s.stats.acks} have been acknowledged. ${learnedCount ? `Human-reviewed patterns guide ${learnedCount} scoped suppression rules across five zones.`:'No suppression is allowed without a human false-alarm verdict.'} ${s.stats.suppressed} matching low-confidence detections were retained as evidence without firing a new alert.`;s.context_metrics.estimated_naive_tokens=Math.ceil(s.context_metrics.naive_bytes/4);s.context_metrics.state_bytes=Buffer.byteLength(JSON.stringify(s));s.context_metrics.estimated_state_tokens=Math.ceil(s.context_metrics.state_bytes/4)}
 ingest(input,override){const raw=validateEvent(input);const existing=this.events.get(raw.event_id);if(existing){if(!isDeepStrictEqual(existing.raw,raw))throw new HttpError(409,'event_id already exists with different content');return copy(existing)}
  const s=this.state,z=s.zones.find(z=>z.zone_id===raw.zone),p=raw.detector_payload;const rule=this.rules.find(r=>r.rule_id===(override?.rule_id||p.rule_id))||this.rules.find(r=>r.hazard_type===(p.hazard_type||raw.type))||this.rules[0];if(!rule)throw new HttpError(503,'Rules are not loaded');
  const start=performance.now();const confidence=typeof p.confidence==='number'?p.confidence:null;const pattern=p.pattern||'unspecified';const learned=z.suppression_rules.find(r=>r.pattern===pattern&&r.type===raw.type);const violation=Boolean((override?.violation??p.violation)&&!(raw.type==='ppe_violation'&&(p.workers_visible===0||p.all_wearing_hardhats===true)));const suppressed=Boolean(violation&&learned&&confidence!==null&&confidence<z.confidence_threshold&&(override?.suppress??true));
  const severity=z.severity_modifier==='CRITICAL'?5:Math.max(1,Math.min(5,Math.round((override?.severity??(raw.type==='focus4_scenario'?4:3))*z.severity_weight)));
  const decision={...override,violation,severity,rule_id:rule.rule_id,suppress:suppressed,confidence,model_confidence:override?.confidence??null,provider:override?.provider||'deterministic-fallback',latency_ms:override?.latency_ms??Number((performance.now()-start).toFixed(3)),reason:suppressed?`Matched human-reviewed pattern: ${pattern}`:'Human review required; no matching low-confidence suppression'};
  const enrichment={rule_id:rule.rule_id,osha_citation:rule.osha_citation,severity,recommended_action:rule.recommended_action,alert_text:violation?`${p.description} ${rule.recommended_action}`:'No PPE concern reported in this frame.',writer:'template'};
  const e={...raw,raw,decision,enrichment,suppressed,verdict:null,acknowledged:false};
  if(s.shift_date!==now().slice(0,10)){s.shift_date=now().slice(0,10);s.stats={events_today:0,acks:0,false_alarms:0,confirmed:0,suppressed:0,total_alerts:0}}s.evidence_count=(s.evidence_count??s.stats.events_today)+1;s.stats.events_today++;s.context_metrics.naive_bytes+=Buffer.byteLength(JSON.stringify(raw));z.last_change_ts=now();
  if(violation&&!suppressed){s.stats.total_alerts++;s.open_alert_count++;z.open_alert_count=(z.open_alert_count||0)+1;z.unacknowledged_count=(z.unacknowledged_count||0)+1;s.open_alerts.unshift({event_id:e.event_id,type:e.type,zone:e.zone,ts:e.ts});s.open_alerts=s.open_alerts.slice(0,12);if(!z.active_hazards.includes(rule.hazard_type))z.active_hazards.push(rule.hazard_type);z.status='alert_open'}else if(suppressed)s.stats.suppressed++;
  return this.commit(e,[{...raw,kind:'detection'},{kind:'enrichment',event_id:e.event_id,ts:now(),enrichment,decision,suppressed}]);
 }
 enrich(id,{alert_text,shift_summary}){const e=this.get(id);if(typeof alert_text!=='string'||typeof shift_summary!=='string'||alert_text.length>700||shift_summary.length>700)invalid('Invalid Liquid enrichment');e.enrichment={...e.enrichment,alert_text,writer:'Liquid LFM2.5-VL-450M'};return this.commit(e,[{kind:'enrichment',event_id:id,ts:now(),enrichment:e.enrichment,decision:e.decision,suppressed:e.suppressed}],shift_summary)}

 // World-model input: only extracted weather fields enter the card. Cranes have wind limits, so an advisory or wind above 25 mph escalates the crane zone.
 setWeather(w){const s=this.state,crane=s.zones.find(z=>z.zone_id==='ZONE-A');const escalate=w.advisory===true||w.wind_mph>25;s.weather={wind_mph:w.wind_mph,advisory:w.advisory,summary:w.summary,source:w.source,updated_ts:w.updated_ts};crane.severity_modifier=escalate?'CRITICAL':'NORMAL';crane.weather_reason=escalate?`Crane wind limit: ${w.advisory?'wind advisory active':w.wind_mph+' mph wind'}`:null;crane.last_change_ts=w.updated_ts;s.revision++;this.rewrite();return copy(s.weather)}
 setRulesVersion(v){this.state.rules_version=v;this.state.revision++;this.rewrite();return copy(v)}
 static fromSnapshot(snapshot,rules){const e=new Engine(null,rules);if(snapshot?.state)e.state=copy(snapshot.state);e.events=new Map((snapshot?.events||[]).map(v=>[v.event_id,copy(v)]));if(snapshot?.outbox?.length)e.transactions=[{records:copy(snapshot.outbox)}];return e}
 snapshot(){return {state:copy(this.state),events:[...this.events.values()].slice(-200).map(copy),outbox:this.pending().flatMap(tx=>tx.records).map(copy)}}
 correction(id,input){const e=this.get(id);if(!e.decision.violation||e.suppressed||e.verdict==='false_alarm')throw new HttpError(409,'Only active hazard observations can receive corrective actions');const statuses=['open','in_progress','completed'];if(!statuses.includes(input.status))invalid('Invalid corrective action status');for(const key of ['action','owner'])if(typeof input[key]!=='string'||!input[key].trim()||input[key].length>2000)invalid(`${key} is required`);for(const key of ['notes','verified_by'])if(input[key]!==undefined&&(typeof input[key]!=='string'||input[key].length>2000))invalid(`Invalid ${key}`);if(input.due_date&&!Number.isFinite(Date.parse(input.due_date)))invalid('Invalid due date');if(input.status==='completed'&&(!input.verified_by?.trim()||!Number.isFinite(Date.parse(input.completed_at))))invalid('Verified completion requires verified_by and completion timestamp');if(input.status==='completed'&&Date.parse(input.completed_at)>Date.now()+60000)invalid('Completion timestamp cannot be in the future');const z=this.state.zones.find(z=>z.zone_id===e.zone);const closed=input.status==='completed';if(closed&&!e.closed){this.state.open_alert_count=Math.max(0,this.state.open_alert_count-1);z.open_alert_count=Math.max(0,(z.open_alert_count||0)-1);if(!e.acknowledged)z.unacknowledged_count=Math.max(0,(z.unacknowledged_count||0)-1);this.state.open_alerts=this.state.open_alerts.filter(a=>a.event_id!==id)}else if(!closed&&e.closed){this.state.open_alert_count++;z.open_alert_count=(z.open_alert_count||0)+1;if(!e.acknowledged)z.unacknowledged_count=(z.unacknowledged_count||0)+1;this.state.open_alerts.unshift({event_id:e.event_id,type:e.type,zone:e.zone,ts:e.ts});this.state.open_alerts=this.state.open_alerts.slice(0,12)}e.closed=closed;e.corrective_action={action:input.action.trim(),owner:input.owner.trim(),due_date:input.due_date||null,status:input.status,completed_at:closed?input.completed_at:null,verified_by:closed?input.verified_by.trim():null,notes:input.notes||'',updated_at:now()};z.status=z.unacknowledged_count?'alert_open':z.open_alert_count?'acknowledged':'clear';if(!z.open_alert_count)z.active_hazards=[];z.last_change_ts=now();return this.commit(e,[{kind:'correction',event_id:id,ts:now(),corrective_action:e.corrective_action,closed}])}
 person(id,input){const e=this.get(id);if(typeof input.label!=='string'||input.label.length>120)invalid('Person label must be at most 120 characters');e.person_label=input.label.trim();e.person_label_source='human-entered; identity not verified by the model';e.person_label_updated_at=now();return this.commit(e,[{kind:'person',event_id:id,ts:now(),person_label:e.person_label,person_label_source:e.person_label_source}])}
 get(id){const e=this.events.get(id);if(!e)throw new HttpError(404,'Event not found');return copy(e)}
 verdict(id,verdict){if(!['confirmed','false_alarm'].includes(verdict))invalid('Invalid verdict');const e=this.get(id);if(!e.decision.violation||e.suppressed)throw new HttpError(409,'Only emitted alerts can receive verdicts');if(e.verdict){if(e.verdict===verdict)return e;throw new HttpError(409,'This event already has a verdict')}
  e.verdict=verdict;const s=this.state,z=s.zones.find(z=>z.zone_id===e.zone);if(verdict==='confirmed'){s.stats.confirmed++;z.severity_weight=Math.min(1.75,z.severity_weight+.25)}else{s.stats.false_alarms++;if(!e.closed){s.open_alert_count=Math.max(0,s.open_alert_count-1);z.open_alert_count=Math.max(0,(z.open_alert_count||0)-1);if(!e.acknowledged)z.unacknowledged_count=Math.max(0,(z.unacknowledged_count||0)-1)}e.closed=true;s.open_alerts=s.open_alerts.filter(a=>a.event_id!==id);z.confidence_threshold=Math.min(.95,Number((z.confidence_threshold+.15).toFixed(2)));const pattern=e.detector_payload.pattern;
   if(pattern){z.suppression_rules=z.suppression_rules.filter(r=>!(r.pattern===pattern&&r.type===e.type));z.suppression_rules.unshift({pattern,type:e.type,learned_from:id,rule:`For ${pattern} in ${e.zone}, retain evidence but suppress alerts below the human-adjusted threshold.`,created_at:now()});z.suppression_rules=z.suppression_rules.slice(0,8)}
   z.status=z.unacknowledged_count?'alert_open':z.open_alert_count?'acknowledged':'clear';if(!z.open_alert_count)z.active_hazards=[]
  }z.last_change_ts=now();return this.commit(e,[{kind:'verdict',event_id:id,ts:now(),verdict}]);
 }
 ack(id){const e=this.get(id);if(e.acknowledged)return e;if(!e.decision.violation||e.suppressed)throw new HttpError(409,'Only emitted alerts can be acknowledged');e.acknowledged=true;e.acknowledged_at=now();this.state.stats.acks++;const z=this.state.zones.find(z=>z.zone_id===e.zone);if(!e.closed)z.unacknowledged_count=Math.max(0,(z.unacknowledged_count||0)-1);z.status=z.unacknowledged_count?'alert_open':z.open_alert_count?'acknowledged':'clear';return this.commit(e,[{kind:'ack',event_id:id,ts:now(),acknowledged:true}])}
 feed(){const alerts=[...this.events.values()].filter(e=>e.decision.violation&&!e.suppressed);const confirmed=alerts.filter(e=>e.verdict==='confirmed').length;const reviewed=alerts.filter(e=>e.verdict).length;return {events:[...this.events.values()].reverse().slice(0,100).map(copy),source:'local',metrics:{confirmed,total_alerts:alerts.length,precision:alerts.length?confirmed/alerts.length:null,reviewed,reviewed_precision:reviewed?confirmed/reviewed:null}}}
 pending(){return this.transactions.slice(this.synced)}
 checkpoint(){this.synced++;if(!this.dir)return;writeFileSync(join(this.dir,'outbox-checkpoint.tmp'),JSON.stringify({synced:this.synced}));renameSync(join(this.dir,'outbox-checkpoint.tmp'),join(this.dir,'outbox-checkpoint.json'))}
}
